name: CI
on:
  pull_request:
  push:

jobs:
  ci:
    runs-on: ubuntu-22.04
    permissions:
        id-token: write
        contents: read
    steps:
    - uses: actions/checkout@main
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Build all derivations
      run: ./build-all.sh
    - name: Run `nix fmt`
      run: nix fmt -- --check .